//
// Created on: 2024/11/6, 15:26.
// Author: Zimeng LI (zimengli@mail.nwpu.edu.cn)
// Project: cgui
//

#ifndef CGUI_ERROR_MSG_H
#define CGUI_ERROR_MSG_H

#define CGUI_ERROR_ILLEGAL_NULL_PTR_MESSAGE "Used null pointer where a non-null pointer was expected."
#define CGUI_ERROR_ILLEGAL_NULL_PTR_CODE 0x00000001

#define CGUI_ERROR_NOT_IMPLEMENTED_MESSAGE "Not implemented."
#define CGUI_ERROR_NOT_IMPLEMENTED_CODE 0x00000002

#define CGUI_ERROR_INVALID_ARGUMENT_MESSAGE "Invalid argument."
#define CGUI_ERROR_INVALID_ARGUMENT_CODE 0x00000003

#define CGUI_ERROR_MEMORY_ALLOCATION_FAILED_MESSAGE "Memory allocation failed."
# define CGUI_ERROR_MEMORY_ALLOCATION_FAILED_CODE 0x00000004

#define CGUI_WINDOW_CLASS_REGISTRATION_FAILED_MESSAGE "Window class registration failed."
#define CGUI_WINDOW_CLASS_REGISTRATION_FAILED_CODE 0x00000011

#define CGUI_WINDOW_CREATE_FAILED_MESSAGE "Window creation failed."
#define CGUI_WINDOW_CREATE_FAILED_CODE 0x00000012

#define CGUI_WINDOW_CLASS_ALREADY_EXISTS_MESSAGE "Window class already exists."
#define CGUI_WINDOW_CLASS_ALREADY_EXISTS_CODE 0x00000013

#define CGUI_WINDOW_CLASS_NOT_FOUND_MESSAGE "Window class not found."
#define CGUI_WINDOW_CLASS_NOT_FOUND_CODE 0x00000014

#define CGUI_COMPONENT_ID_ALREADY_EXISTS_MESSAGE "Component ID already exists."
#define CGUI_COMPONENT_ID_ALREADY_EXISTS_CODE 0x00000020

#define CGUI_COMPONENT_NOT_FOUND_MESSAGE "Component not found."
#define CGUI_COMPONENT_NOT_FOUND_CODE 0x00000021

#define CGUI_FACTORY_NOT_FOUND_MESSAGE "Factory not found."
#define CGUI_FACTORY_NOT_FOUND_CODE 0x00000030

#endif //CGUI_ERROR_MSG_H
